register/register/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from thereg import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^thereg/',include('thereg.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^logout/$', views.user_logout, name='logout'),
]


from thereg import views
from register import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/thereg/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url
from thereg import views
# SET THE NAMESPACE!
app_name = 'thereg'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^feedback_form/$', views.feedback_form, name='feedback'),
    url(r'^members/$', views.members, name='members'),
    path('', views.PostList.as_view(), name='events'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='event_detail'),
]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/thereg/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
# Create your models here.
YEAR = [('1st','first'),('2nd','second'),('3rd','third'),('4th','fourth'),('HS or Lower','HS or Lower'),('grad','Graduate'),('PG','Post-Graduate')]

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='UserProfileInfo')
	Institute = models.CharField(max_length=200,blank=True)
	Department = models.CharField(max_length=200,blank=True)
	Year = models.CharField(max_length=13,choices=YEAR)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
		return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])

	post_save.connect(create_profile, sender=User)



class Feedback(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    message = models.TextField()
    
    date = models.DateField(auto_now_add=True)
 
    def __str__(self):
        return self.name







STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    image = models.ImageField(upload_to='media/img',blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

register/thereg/forms.py
from django import forms
from thereg.models import UserProfileInfo 
from thereg.models import Feedback
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('Institute','Department','Year','profile_pic')






class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

register/thereg/views.py
from django.shortcuts import render , redirect
from thereg.models import Feedback,Post
# Create your views here.
from django.shortcuts import render
from thereg.forms import UserForm,UserProfileInfoForm,FeedbackForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views import generic
def index(request):
    form = FeedbackForm()
    return render(request,'thereg/index2.html', {'feedbackform': form})
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'thereg/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'thereg/login.html', {})






def feedback_form(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'thereg/index2.html', {'feedbackform': form})
    else:
        form = FeedbackForm()
    return render(request, 'thereg/index2.html', {'feedbackform': form})




def members(request):
    
    return render(request,'thereg/members.html',{})


class PostList(generic.ListView):
    model = Post
    template_name = 'thereg/events.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'thereg/event_detail.html'

register/templates/thereg/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

   <meta charset="utf-8">
    <title>IEEE_NIT_Dgp</title>
    <meta name="description" content="">
    <meta name="IEEE-sb" content="">

    <!-- mobile specific metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    

<link href="https://fonts.googleapis.com/css?family=Arvo|Inconsolata|Merriweather+Sans|ZCOOL+QingKe+HuangYou" rel="stylesheet">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <style type="text/css">
      *{
        
        box-sizing: border-box;
        
      }
  body{
    overflow-x: hidden;
  }
     /*light theme*/
              body.light_body::-webkit-scrollbar {
  background: #999999;
  opacity: 0.6; 
  width: 20px;
}

/* Handle */
body.light_body::-webkit-scrollbar-thumb {
  background: #d9d9d9; 
  border-radius: 5px;

}

/* Handle on hover */
body.light_body::-webkit-scrollbar-thumb:hover {
  background: #efefef; 
}



      /*dark theme*/
      body.dark_body::-webkit-scrollbar {
  background: rgba(180,180,180,0.5);
  opacity: 0.6; 
  width: 20px;
}

/* Handle */
body.dark_body::-webkit-scrollbar-thumb {
  background: #dadadf; 
  border-radius: 5px;

}

/* Handle on hover */
body.dark_body::-webkit-scrollbar-thumb:hover {
  background: #eaeaef; 
}




      html,body{
        margin: 0;
        padding: 0;
      }
      section{
        width: 95vw;
        overflow-x: hidden;
        box-sizing: border-box;
      }
       *::before,*::after{
          box-sizing: border-box;
        }

        main{
          width: 100%;
          overflow-x: hidden;
          margin: 0 auto;
        }
        


      


        .light_main_back::before{
         
          background-color: #fff;
                  }
           .light_main_back::after{
          
          background-color: rgba(0,0,50,0.5);


        }









        .dark_main_back::before{
           background-color: #000;
        }
           .dark_main_back::after{
        background-color: rgba(0,0,50,0.5);
        border-color: #F0404e;
        }






       

input.login:hover{
 background-color: rgba(255,255,255,0.4);
}




/*slider*/

















/*header*/

/*header*/
header{
  position: fixed;
  top: 0;
  color: #fff;
  z-index: 22222;
  width: 100vw;
  font-family: 'Merriweather Sans', sans-serif;
  letter-spacing: 2px;
  transition: all 0.4s ease-in-out;
  background-color: rgba(0,0,0,0.5);
  height: 120px;
  overflow: hidden;

}
header ul{
list-style: none;
position: fixed;
right: 70px;
cursor: pointer;
z-index: 22222;
left: ;
margin-top: 0px;
text-decoration: none;
padding-left: 0;
padding-top: 0;
  color: #fff;
  transition: all 0.8s ease-in-out;

}
header ul li{
  display: inline-block;
  margin: 3px;
  cursor: pointer;
  background-color: rgba(0,0,0,0);
  border-radius: 0px;
  padding: 2px;
  transition: all 0.15s ease-in-out;

}
header ul li:hover{
  background-color: rgba(0,0,0,0);
  
  letter-spacing: 0.15em;
}
header ul li a{
    text-decoration: none;
  color: #fff;
}

header ul li a:hover{
  color: #aaf;
  text-decoration: none;
}

.helptext{

  font-size: 10px;
  font-family: monospace;

}


input#id_username:focus{

}
input#id_username:hover>.helptext{
  display: block;
}







/*side bar*/




section span{
  color: #f24;
  text-decoration: none;
}


.light_body{
  background-color: rgba(47, 109, 155,0.9);
}
.dark_body{
  background-color: rgba(46, 25, 155,0.8);
}

.light_body .reg-container{
  margin-top:15vh;
  max-width: 90vw;
  background-color: rgba(47, 109, 155,0.9);
  padding: 50px;
}


.light_body .reg-container .jumbotron{
  
  background-color: rgba(117, 209, 255,0);
}
.dark_body .reg-container{
   margin-top:15vh;
  max-width: 90vw;
  background-color: rgba(46, 25, 155,0.8);
  padding: 50px;
}
.dark_body .reg-container .jumbotron{
  background-color: rgba(136, 85, 255,0);
}


.reg-container .jumbotron h1{
  color: #fff;
}
.reg-container .jumbotron p span.helptext{
 color: #fff;
}

.reg-container .jumbotron h3{
 color: #fff;
}
.reg-container .jumbotron label{
  display: block;
  color: #fff;
}
.reg-container .jumbotron input{
  display: block;
  transition: all 0.5s ease-in-out;
  color: #000;
  max-width: 100vw;
}
.reg-container .jumbotron input:focus{
  border-radius: 5px;
}
input.regis-sub{
  background-color: rgba(200,200,200,0.5);
  border: 1px solid #fff;
  border-radius: 25px;
  padding: 10px 20px;
  color: #fff;
  font-weight: 700;

}
input.regis-sub:hover{
  background-color: rgba(0,0,0,0.3);
}










@media only screen and (max-width:880px) {

  section {
    
    margin: 0 auto;

  }
  main{
     margin: 0 auto;
     padding: 0;
     box-sizing: border-box;
  }
  

header{
  width: 100vw;
}

header ul{
background-color: rgba(0,0,0,0.2);

}
header ul li{
 font-size: 9px;
 float: right;
}

header img{
  width: 90px;
  margin-top: 0px;
  margin-left: 0px;
}


.reg-container input{
  width: 55vw;
}








}

































@media only screen and (max-width:1280px) and (min-width:900px){




 .background_main img{
  height: 100%;
 }



section.about_ieee h4{

  font-size: 17px;
  

}
section.about_ieee p{
  
  font-size: 12px;
  word-spacing: 0.7em;
  

}

}

    </style>

</head>
<body class="light_body">
<header style="display: block;">
  <div class="logo" style="float: left; padding-left: 30px;"><img src= "http://i.xp.io/yO2IRLu.svg+xml" height="140px"></div>
  <ul id="header-list" style="float: right; padding-top: 30px;">
    <!--/media/images/ieeesb_logo.svg-->

          <li><a class="navbar" href="{% url 'index' %}">Home</a></li>
           <li><a class="navbar" href="{% url 'thereg:events' %}">Events</a></li>

            <li><a class="navbar" href="">Notifications</a></li>
          
          <li><a class="navbar" href="{% url 'admin:index' %}">Admin</a></li>
               
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="#">Welcome {{ user.username }}!</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            
          {% else %}
          <li><a class="navbar" href="{% url 'thereg:register' %}">Register</a></li>
            <li><a class="navbar" href="{% url 'thereg:user_login' %}">Login</a></li>
          {% endif %}
    </ul>
</header>



 <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


<div id="top" style="position: fixed; z-index: 99999;cursor: pointer;bottom: 50px; right:20px;transform: rotate(-90deg) scale(0); padding:5px 10px; background-color: rgba(100,100,100,0.6);border-radius: 5px ;font-size: 30px; color: #fff; font-family: monospace; text-align: center; transition: all 0.4s;">></div>

<div class="switch_container" style="position: fixed; z-index: 99999;cursor: pointer;bottom: 50px; left:60px; background-color: rgba(100,100,100,1);border-radius: 5px ;font-size: 12px; color: #fff; font-family: monospace; display: grid; grid-template-columns: 1fr 1fr;">
  <div id="dark" style="display: block; width: 30px; text-align: center;">o</div>
<div id="light" style="display: block; width: 30px; background-color: #27f; text-align: center;"></div>
</div>





</body>

































<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>


<script type="text/javascript">
  jQuery(document).ready(function ($){

    $(".scroll_tag").click(function(){
      
      var offsetHeight = document.getElementById('home').offsetHeight; 
      window.scroll(0, offsetHeight*1.15);
      
    })
  })
</script>





<script type="text/javascript">
  

    $("#top").click(function(){
    window.scroll(0, 0);
    });
    
    
  
</script>






<!--dark/light theme animation-->
<script type="text/javascript">
  

    $("#dark").click(function(){

      $("body").css("background-color", "#000");
      
      
      $("section.about_ieee #about_division").css("background-color", "#222");
      $("section.about_ieee #about_division .about_content_half").css("color", "#fff");
      $(".join_ieee").css("color", "#fff");
      $(".events_ieee").css("color", "#fff");
           $("#dark").css("background-color", " #27f");
     document.getElementById("dark").innerHTML="";
     document.getElementById("light").innerHTML="o";
     $("#light").css("background-color", "rgba(100,100,100,1)");
   
         $(".background_main").addClass("dark_main_back").removeClass("light_main_back");
         $("body").removeClass("light_body").addClass("dark_body");

    });
  
    
    
  
</script>





<script type="text/javascript">
  

    $("#light").click(function(){
      $("body").css("background-color", "");
      $(".background_main::after").css("background-color", "");
      $(".background_main::before").css("background-color", "");
      $("section.about_ieee #about_division").css("background-color", "");
      $("section.about_ieee #about_division .about_content_half").css("color", "");
      $(".join_ieee").css("color", "");
      $(".events_ieee").css("color", "");
       $("#light").css("background-color", " #27f");
     document.getElementById("dark").innerHTML="o";
     document.getElementById("light").innerHTML="";
     $("#dark").css("background-color", "rgba(100,100,100,1)");
      $(".background_main").removeClass("dark_main_back").addClass("light_main_back");
             $("body").removeClass("dark_body").addClass("light_body");
      
     
    });
  
    
    
  
</script>

<!--end theme-->






 


























    <script type="text/javascript">
      $(window).scroll(function(){
        var scrollTop = $(window).scrollTop();
        if(scrollTop>50){
          $("#top").css("transform", " rotate(-90deg) scale(1)")
        }
        else{
          $("#top").css("transform", " rotate(-90deg) scale(0)")}
      })
    </script>












<!--scrollanimation-->











  <script>
      function ErrorPage(e,t,n){this.$container=$(e),this.$contentContainer=this.$container.find(n=="sign"?".sign-container":".content-container"),this.pageType=t,this.templateName=n}ErrorPage.prototype.centerContent=function(){var e=this.$container.outerHeight(),t=this.$contentContainer.outerHeight(),n=(e-t)/2,r=this.templateName=="sign"?-100:0;this.$contentContainer.css("top",n+r)},ErrorPage.prototype.initialize=function(){var e=this;this.centerContent(),this.$container.on("resize",function(t){t.preventDefault(),t.stopPropagation(),e.centerContent()}),this.templateName=="plain"&&window.setTimeout(function(){e.$contentContainer.addClass("in")},500),this.templateName=="sign"&&$(".sign-container").animate({textIndent:0},{step:function(e){$(this).css({transform:"rotate("+e+"deg)","transform-origin":"top center"})},duration:1e3,easing:"easeOutBounce"})},ErrorPage.prototype.createTimeRangeTag=function(e,t){return"<time utime="+e+' simple_format="MMM DD, YYYY HH:mm">'+e+"</time> - <time utime="+t+' simple_format="MMM DD, YYYY HH:mm">'+t+"</time>."},ErrorPage.prototype.handleStatusFetchSuccess=function(e,t){if(e=="503")$("#replace-with-fetched-data").html(t.status.description);else if(!t.scheduled_maintenances.length)$("#replace-with-fetched-data").html("<em>(there are no active scheduled maintenances)</em>");else{var n=t.scheduled_maintenances[0];$("#replace-with-fetched-data").html(this.createTimeRangeTag(n.scheduled_for,n.scheduled_until)),$.fn.localizeTime()}},ErrorPage.prototype.handleStatusFetchFail=function(e){$("#replace-with-fetched-data").html("<em>(enter a valid StatusPage.io url)</em>")},ErrorPage.prototype.fetchStatus=function(e,t){if(!e||!t||t=="404")return;var n="",r=this;t=="503"?n=e+"/api/v2/status.json":n=e+"/api/v2/scheduled-maintenances/active.json",$.ajax({type:"GET",url:n}).success(function(e,n){r.handleStatusFetchSuccess(t,e)}).fail(function(e,n){r.handleStatusFetchFail(t)})};
      var ep = new ErrorPage('body', "503", "plain");
      ep.initialize();
      // hack to make sure content stays centered >_<
      $(window).on('resize', function() {
        $('body').trigger('resize')
      });
    </script>












<!--slider events-->

 





<script type="text/javascript">
  /*jQuery(document).ready(function ($){

   var itemHeight = $("header ul").height();
   var notifyHeight = $("#notify").width();
   itemHeight=  itemHeight + 20;
   
if(window.matchMedia('(min-width: 880px)').matches){
   
   
   $("header img").css("height", (itemHeight*2 +"px"));
   $("header img").css("margin-left", (15 +"px"));}
else if(window.matchMedia('(max-width: 880px)').matches){

  $('header ul').css("width", notifyHeight+40+"px");
}
  


}) */
</script>
</html>
    
  </body>
</html>

register/templates/thereg/event_detail.html
{% extends 'thereg/eventbase.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
        
         {% if not post.image.isempty %}
                     
                    
              <img src="{{ MEDIA_URL }}{{ post.image.url }}" alt="img" height="400px;">
         {% endif %}
         
       
      </div>
    </div>
    
  </div>
</div>

{% endblock content %}

register/templates/thereg/eventbase.html
{% load static %}

<!DOCTYPE html>
<html>

    <head>
        <title>IEEE-SB</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }








        /*header*/
header{
  position: relative;
  top: 0;
  color: #fff;
  z-index: 22222;
  width: 100vw;
  font-family: 'Merriweather Sans', sans-serif;
  letter-spacing: 2px;
  transition: all 0.4s ease-in-out;
  background-color: rgba(0,0,0,1);
  height: 120px;
  overflow: hidden;

}
header ul{
list-style: none;
position: absolute;
right: 70px;
cursor: pointer;
z-index: 22222;
left: ;
margin-top: 0px;
text-decoration: none;
padding-left: 0;
padding-top: 0;
  color: #fff;
  transition: all 0.8s ease-in-out;

}
header ul li{
  display: inline-block;
  margin: 3px;
  cursor: pointer;
  background-color: rgba(0,0,0,0);
  border-radius: 0px;
  padding: 2px;
  transition: all 0.15s ease-in-out;

}
header ul li:hover{
  background-color: rgba(0,0,0,0);
  
  letter-spacing: 0.15em;
}
header ul li a{
    text-decoration: none;
  color: #fff;
}

header ul li a:hover{
  color: #aaf;
  text-decoration: none;
}
    </style>




    <header style="display: block;">
  <div class="logo" style="float: left; padding-left: 30px;"><img src= "http://i.xp.io/yO2IRLu.svg+xml" height="140px"></div>
  <ul id="header-list" style="float: right; padding-top: 30px;">
    <!--/media/images/ieeesb_logo.svg-->

          <li><a class="navbar" href="{% url 'index' %}">Home</a></li>
           <li><a class="navbar" href="{% url 'thereg:events' %}">Events</a></li>

            <li><a class="navbar" href="">Notifications</a></li>
          
          <li><a class="navbar" href="{% url 'admin:index' %}">Admin</a></li>
               
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="#">Welcome {{ user.username }}!</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            
          {% else %}
          <li><a class="navbar" href="{% url 'thereg:register' %}">Register</a></li>
            <li><a class="navbar" href="{% url 'thereg:user_login' %}">Login</a></li>
          {% endif %}
    </ul>
</header>

       <div class="jumbotron">OUR EVENTS</div>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center " style="font-size: 9px;">Copyright &copy; IEEE SB NITDGP</p>
        </footer>
    </body>

</html>

register/templates/thereg/events.html
<!DOCTYPE html>
<html>
{% extends "thereg/eventbase.html" %} 
{% block content %}
<head>
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
       border:0px;
    }


</style></head>
<body>

<div class="container" style="width: 100vw;">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    
                     {% if not post.image.isempty %}
                     
                    
                    <img src="{{ MEDIA_URL }}{{ post.image.url }}" alt="img" style="max-width: 250px">
                    {% endif %}
                    <a href="{% url 'thereg:event_detail' post.slug  %}" class="btn btn-default float-right">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{%endblock%}
</body>
</html>

register/templates/thereg/index.html
{% extends "thereg/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

register/templates/thereg/login.html
{% extends 'thereg/base.html' %}
{% block body_block %}
  <div class="container reg-container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'thereg:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login" style="background-color: transparent; border: 2px solid #fff; border-radius: 25px; margin-top: 15px; color: #fff; width: 120px;" class="login">
</form>


   <br>
  <p></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-decoration: none; color: #fff; display: block; padding: 10px; background-color: rgba(0,0,0,0.2); width: 200px; text-align: center; border-radius: 20px;"><i class="fa fa-google" style="font-size: 18px; padding-right: 2px;"></i>   Login with Google</a><br>
</div>
  </div>
{% endblock %}

register/templates/thereg/registration.html
{% extends "thereg/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container reg-container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register" class="regis-sub" style="color: #fff;">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}